spring.application.name=kdAPIs

# Core Database Configuration
spring.datasource.core.hikari.jdbc-url=jdbc:sqlserver://localhost:1433;databaseName=IQA;encrypt=true;trustServerCertificate=true;sendStringParametersAsUnicode=false;
spring.datasource.core.hikari.username=sa1
spring.datasource.core.hikari.password=Cdit@mothai34nam
spring.datasource.core.hikari.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.core.hikari.maximum-pool-size=10
spring.datasource.core.hikari.connection-timeout=30000
spring.datasource.core.hikari.leak-detection-threshold=20000

# Evidence Database Configuration
spring.datasource.evidence.hikari.jdbc-url=jdbc:sqlserver://localhost:1433;databaseName=kiemdinh;encrypt=true;trustServerCertificate=true;sendStringParametersAsUnicode=false;
spring.datasource.evidence.hikari.username=sa1
spring.datasource.evidence.hikari.password=Cdit@mothai34nam
spring.datasource.evidence.hikari.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.evidence.hikari.maximum-pool-size=10
spring.datasource.evidence.hikari.connection-timeout=30000
spring.datasource.evidence.hikari.leak-detection-threshold=20000

# Query Timeout configuration (10 seconds)
spring.jdbc.template.query-timeout=10

# Hibernate settings (if needed later)
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# Customizes the path for the raw OpenAPI JSON metadata
springdoc.api-docs.path=/api-docs

# Forces Swagger UI to prepend the service name to the execution paths
# springdoc.server.url=/kdAPIs
server.servlet.context-path=/kdAPIs

server.shutdown=graceful
spring.lifecycle.timeout-per-shutdown-phase=30s


# API key for Slink (if needed)
slink.api-key="4sUgLOsrtFOkjQ84ar9kvVwjByhAiQPs"

# Customizes the path for the interactive user UI
springdoc.swagger-ui.path=/swagger-ui.html

server.port=8080
